Add objects365 dataset
Nota-NetsPresso/netspresso-trainer pull request #482
Opened 2024-08-02 04:25 UTC by hglee98

## Description

Please include a summary of this pull request in English. If it closes an issue, please mention it here.

Closes: #481

We recommend to link at least one existing issue for PR. Before your create a PR, please check if there is an issue for this change.  

## Change(s)

- (Please write a description for this change.)

## Code Formatting

If you PR to either `master` or `dev` branch, you should follow the code linting process. Please check your code with `lint_check.sh` in `./scripts` directory.
For more information, please read the contribution guide in `CONTRIBUTING.md`. 

## Changelog

If your PR is granted to `dev` branch, codeowner will add a brief summary of the change to the **Upcoming Release** section of the [`CHANGELOG.md`](https://github.com/Nota-NetsPresso/netspresso-trainer/blob/master/CHANGELOG.md) file including a link to the PR (formatted in markdown) and a link to your github profile.

For example,

```
- Added a new feature by `@myusername` in [PR 2023](https://github.com/Nota-NetsPresso/netspresso-trainer/pull/2023)
```

Please enable **Allow edits and access to secrets by maintainers** so that our maintainers can update the `CHANGELOG.md`.

2024-08-08 08:56 UTC, illian01 requested changes
I have few suggests about this PR.
Please check detailed review.

2024-08-08 08:56 UTC, illian01 commented on tools/open_dataset_tool/objects365.py
> +                time.sleep(delay)
Can you add retry log more explicitly? For example, 

```suggestion
        except subprocess.CalledProcessError as e:
            print(f"Attempt {attempt + 1} failed to download {url}: {e}")
            print(f"Retry download after {delay} seconds ...")
            if attempt < max_retries - 1:
                time.sleep(delay)
```

2024-08-08 08:56 UTC, illian01 commented on tools/open_dataset_tool/objects365.py
> +DOWNLOAD_DIR = './data/download'
I think Objects365 dataset has so many data split to download. How about changing download target path to `./data/download/objects365`?

```suggestion
DOWNLOAD_DIR = './data/download/objects365'
```

2024-08-08 13:25 UTC, hglee98 commented
Thank you for your kind review! I appreciate it :) I reflect your review and revise the source codes.

2024-08-09 06:47 UTC, illian01 approved these changes
LGTM!

2024-08-09 06:47 UTC, merged